# Generated by Django 2.2 on 2020-10-16 01:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('idCity', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('idProperty', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('maxPax', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('image', models.ImageField(upload_to='property')),
                ('dailyCost', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentalProperty.City')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('idReservation', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('lastName', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=200)),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField()),
                ('totalCost', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentalProperty.Property')),
            ],
            options={
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='RentalDate',
            fields=[
                ('idRentalDate', models.AutoField(primary_key=True, serialize=False)),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField()),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentalProperty.Property')),
            ],
            options={
                'verbose_name_plural': 'RentalDates',
            },
        ),
    ]
