# Generated by Django 2.2 on 2020-10-20 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalProperty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentalProperty.Property'),
        ),
    ]
