# Generated by Django 2.2.6 on 2020-10-23 01:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentalProperty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentaldate',
            options={'ordering': ('date', 'property'), 'verbose_name_plural': 'RentalDates'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 23, 1, 17, 51, 548215, tzinfo=utc)),
        ),
    ]
