# Generated by Django 2.2.6 on 2020-10-22 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalProperty', '0002_auto_20201020_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldate',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rentalProperty.Reservation'),
        ),
    ]
