# Generated by Django 2.2.6 on 2020-10-23 01:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentalProperty', '0002_auto_20201022_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 23, 1, 50, 58, 110147, tzinfo=utc)),
        ),
    ]
