# Generated by Django 2.2.6 on 2020-10-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalProperty', '0002_auto_20201022_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
