# Generated by Django 2.2.6 on 2020-10-23 01:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentalProperty', '0003_auto_20201022_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 23, 1, 53, 5, 613428, tzinfo=utc)),
        ),
    ]
