# Generated by Django 2.2.6 on 2020-10-23 01:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentalProperty', '0004_auto_20201022_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 23, 1, 55, 49, 454246, tzinfo=utc)),
        ),
    ]
