# Generated by Django 2.2 on 2020-10-23 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentalProperty', '0005_auto_20201022_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 23, 2, 44, 39, 940796, tzinfo=utc)),
        ),
    ]
